experiment_id: canary_simulation

data:
  alphabet: ['<', 'p0', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 'p11', 'p12', 'p13', 'p14', 'p15', 'p16', 'p17', 'p18', 'p19', 'p20', 'p21', 'p22', 'p23', 'p24', 'p25', 'p26', 'p27', 'p28', 'p29', 'p30', 'p31', 'p32', 'p33', 'p34', 'p35', 'p36', 'p37', '>']
  order: 1
  n_sequences: 1000
  max_length: 40
  evolution_type: piecewise

em:
  max_iterations: 40
  tolerance: 1e-4
  regularization_lambda: 0.001 