experiment_id: oscillatory_evolution

data:
  alphabet: ['<', 'a', 'b', 'c', 'd', 'e', '>']
  order: 1
  n_sequences: 80
  max_length: 20
  evolution_type: oscillatory

em:
  max_iterations: 20
  tolerance: 1e-4
  regularization_lambda: 0.001 