experiment_id: oscillatory_evolution

data:
  alphabet: ['<', 'a', 'b', 'c', '>']
  order: 1
  n_sequences: 100
  max_length: 40
  evolution_type: oscillatory

em:
  max_iterations: 100
  tolerance: 1e-6
  regularization_lambda: 0.001 
  damping_factor: 0.1 
  adaptive_damping: true
  
